wordpressUsername: user

wordpressPassword: ""

wordpressEmail: mazurovsasha@gmail.com

wordpressBlogName: Mazurov's Blog!

wordpressFirstName: Aleksandr
wordpressLastName: Mazurov

ingress:

  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/server-alias: "wordpress.k8s-7.sa"
  hosts:
    - host: wordpress.k8s-7.sa
      paths:
        - path: /
          pathType: ImplementationSpecific


mariadb:
  enabled: false
  replication:
    enabled: false

externalDatabase:
  host: 192.168.202.14
  user: sasha@%
  password: "12345678"
  database: wordpressdb
  port: 3306 