drupalUsername: user

drupalPassword: ""


ingress:

  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/server-alias: "drupal.k8s-7.sa"
  hosts:
    - host: drupal.k8s-7.sa
      paths:
        - path: /
          pathType: ImplementationSpecific


mariadb:
  enabled: false
  # replication:
  #   enabled: false

externalDatabase:
  host: 192.168.202.14
  user: sasha
  password: "12345678"
  database: drupaldb
  port: 3306
  existingSecret: "" 